### ISSUE TITLE
Plugin on idea repository is  missing

### ISSUE THREAD

**Issue by sinceow** [henjue/vue-for-idea#64]
https://plugins.jetbrains.com/plugin/8123?pr=idea

**Comment by piotros** [comment]
JetBrains developers deleted vue-for-idea from their repository because of significant bug reported by the community and lack of cooperation from author side. This topic may interest you: https://github.com/henjue/vue-for-idea/issues/46. Especially this comments: https://github.com/henjue/vue-for-idea/issues/46#issuecomment-245241199, https://github.com/henjue/vue-for-idea/issues/46#issuecomment-251399568.

**Comment by mtio** [comment]
It's to bad. I liked this plugin more.

**Comment by deangoku** [comment]
I loved this plugin too. Is there any chance @henjue can republish this plugin to repository or release a zip for local installation?

**Comment by springeye** [comment]
fixed！
